### ISSUE TITLE
A question about the results in the paper

### ISSUE THREAD

**Issue by Liuyaqi99** [ISEE-Technology/lidar-with-velocity#1]
Hello, I'm interested in your work!
While reading your paper, I have a question that I hope I can get an answer from you.
In the results of your system (Fig 9，especially the two pictures on the left), I noticed there are some noise at the rail of the green point cloud (corrected point cloud). I would like to ask if this noise is caused by the motion distortion correction or the inaccurate object detection/clustering results?
Thanks!

您好，我对你们的工作很感兴趣！
在阅读你们的论文时，我有一个问题，希望可以得到你们的解答。
在你们的系统输出结果中（Fig 9，左边两张图比较明显），我注意到了在绿色的点云（矫正后的点云）的尾部有一些噪点，我想请问下这个噪点是因为畸变矫正产生的还是因为检测/分割的不够准确而产生的呢？
感谢！

**Comment by yangwen-1102** [comment]
Thanks for attention,

There are two reasons for the noise points. One is the detection error, the points of the near ground may be assigned incorrectly to the object. The other is that the timestamps of few points are not completely correct. So after undistortion, the point may still have a drift

**Comment by Liuyaqi99** [comment]
Thanks for your answer！
