### ISSUE TITLE
How about the distortion affect detection?

### ISSUE THREAD

**Issue by mjjdick** [ISEE-Technology/lidar-with-velocity#2]
Hi, nice work!

But I have some questions, looking forward your reply.

First of all, the distortion pointcloud may affect the object detection, I think that is the main reason why we must do pointcloud distortion. But in your paper, I understand you do undistortion after the object and MOT, did the reason and result revert?

And the second, throuh we are already get the detection an tracking result, why we need do undistortion then? May be use the boost idea to refine detection result? But I do really think it is cost.  Is there any evaluation about the time and computing resource costing?

And the third, I think the reason why you need camera, may be promote the detection ap or tracking performance. But if the pointcloud is distorted, if the calibration precision will be affected? espically for the long distance(may be 50 miles or 100 miles away?) we known the calibration precision will really low, and then the the calibration precision may be lower!

Thx again, the first question really confuse me and I really hope your help.

**Comment by yangwen-1102** [comment]
Thanks for attention!

For your first question. More than just improving the confidence of detection. The accurate pointcloud can also be used to eliminate the effects of points blur and refine the detection Bbox, which is efficient to following processing such as freespace segmentation and self path planning. Meanwhile, undistortion can also provide the velocity of the object and verify its accuracy, which serves as a better perception of the surroundings. 
What you want to express in the second question seems to be the same as the first one.
For the third question, the calibration is performed in a static scene in first beginning. The distortion will not affect the calibration.

**Comment by mjjdick** [comment]
> Thanks for attention!
> 
> For your first question. More than just improving the confidence of detection. The accurate pointcloud can also be used to eliminate the effects of points blur and refine the detection Bbox, which is efficient to following processing such as freespace segmentation and self path planning. Meanwhile, undistortion can also provide the velocity of the object and verify its accuracy, which serves as a better perception of the surroundings. What you want to express in the second question seems to be the same as the first one. For the third question, the calibration is performed in a static scene in first beginning. The distortion will not affect the calibration.

Thanks for replying！
