### ISSUE TITLE
The maximum frames can be merged

### ISSUE THREAD

**Issue by Psyclonus2887** [ISEE-Technology/lidar-with-velocity#4]
Thank you for your excellent work! From the paper it seems the experiments are done in the consecutive 3 frames of point cloud from Livox Horizon. How much frames can be merged to the maximum? Is that corresponding to the velocity and acceleration of the moving object in the scene?

**Comment by yangwen-1102** [comment]
theoretically any number of frames can be merged. if the velocity is accurate enough, u can merge all the measurements of the object.
