### ISSUE TITLE
The result using your dataset

### ISSUE THREAD

**Issue by Psyclonus2887** [ISEE-Technology/lidar-with-velocity#6]
Hi! I test your code with your dataset, but the result is not as good as that in paper. Is there anything wrong when I use the code?
![image](https://user-images.githubusercontent.com/57947526/159470576-b8935d9c-7846-4052-bde8-650c48dfc213.png)
![image](https://user-images.githubusercontent.com/57947526/159470623-e40a2785-8b39-4be8-8b8c-f74f3e08ce26.png)
As you can see, the distortion of point cloud is not completely compensated.

**Comment by yangwen-1102** [comment]
thanks for the test. Which data does this picture correspond to? Can u provide more infomation and i will check it

**Comment by Psyclonus2887** [comment]
Actually, most of the frames when I testing the dataset has this problem. I just follow the instruction of  how to run the code.

**Comment by yangwen-1102** [comment]
Thank you for your feedback. It seems an older version of code was merged in our previous update. We have updated the code and the data and please double check the result. Again, thanks for your interest and help.

**Comment by Psyclonus2887** [comment]
Thanks for your reply. BTW, where do you submit this paper?

**Comment by yangwen-1102** [comment]
The paper is under review. if you are interested in this, please email me at yangwen1102@foxmail.com. :)
